### ISSUE TITLE
Doesn't handle new error message format correctly

### ISSUE THREAD

**Issue by mkg20001** [4lejandrito/uptimerobot-node-client#2]
When the api key is wrong, uptimerobot returns: 
```xml
<error id="101" message="apiKey is wrong"/>
```

Also sometimes a cloudflare error is returned and that causes:
```js
TypeError: Cannot read property '1' of null
    at parseJSONResponse (/home/maciej/Projekte/sysadmin-notifier/node_modules/uptimerobot-client/index.js:7:44)
    at Request._callback (/home/maciej/Projekte/sysadmin-notifier/node_modules/uptimerobot-client/index.js:35:28)
    at Request.self.callback (/home/maciej/Projekte/sysadmin-notifier/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/maciej/Projekte/sysadmin-notifier/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/maciej/Projekte/sysadmin-notifier/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1085:12)
```

I've quickly hacked together my own client based on yours. You might want to copy the error handler https://github.com/mkg20001/sysadmin-notifier/blob/092be3e0c6b1d0209b6cce50e6f685b3b74f54e3/src/source/uptimerobot/client.js#L38-L51

**Comment by 4lejandrito** [comment]
Hi @mkg20001,

I have added a few tests hitting the real API (see https://github.com/4lejandrito/uptimerobot-node-client/commit/4158b0965b8e4f566f288e8324c92548270c6108) and I get the expected result in JSON except for the case when the api key is not specified which returns a weird ASP error. 

You seem to be asking for XML format instead of JSON.

Thanks!

**Comment by mkg20001** [comment]
@4lejandrito This was indeed the error, although the currently published version of uptimerobot-client still uses the xml method instead of json (uptimerobot-client package seems to have been last published/updated 3 years ago, mind making a new version?).

**Comment by 4lejandrito** [comment]
Hi @mkg20001,

I sent an email to Uptimerobot support team and they fixed the error. I fixed the test in https://github.com/4lejandrito/uptimerobot-node-client/commit/9cb0dcbcdad122161d01db70cb3fc7906f7ee3e9. 

Now the errors should be all well handled. 

Please let me know if you think there is still room for improvement.

**Comment by mkg20001** [comment]
Hi @4lejandrito,

thanks for doing that.

What I meant was that the npm package published here https://www.npmjs.com/package/uptimerobot-client is outdated and needs to be updated to a newer version with the new source code.

**Comment by 4lejandrito** [comment]
You're right, sorry!

Done! 

See https://www.npmjs.com/package/uptimerobot-client/v/0.2.0.
